name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Set up JDK 21
         uses: actions/setup-java@v2
         with:
           java-version: '21'
           distribution: 'temurin'

       - name: Build with Maven
         run: mvn clean package

       - name: Login to Azure Container Registry
         uses: azure/docker-login@v2
         with:
           registry: ${{ secrets.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
           username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
           password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

       - name: Build and push Docker image
         run: |
           docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ github.repository }}:${{ github.sha }} .
           docker push ${{ secrets.AZURE_CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ github.repository }}:${{ github.sha }}
